export enum TasksIds {
  BuildSection = "BuildSection",
  BuildSector = "BuildSector",
  Generate = "Generate",
  Decorate = "Decorate",
  RGBlightUpdate = "RGBlightUpdate",
  RGBlightRemove = "RGBlightRemove",
  WorldSun = "WorldSun",
  SunLightUpdate = "SunLightUpdate",
  SunLightRemove = "SunLightRemove",
  WorldPropagation = "Propagation",
  AnalyzerUpdate = "AnalyzerUpdate",
  FlowUpdate = "FlowUpdate",
  FlowRemove = "FlowRemove",
  ConstructEntity = "ConstructEntity",
  ConstructItem = "ConstructItem",
  Explosion = "Explosion",
  VoxelErase = "VoxelErase",
  VoxelPaint = "VoxelPaint",
  VoxelUpdate = "VoxelUpdate",
  LogicUpdate = "LogicUpdate",
  PropagationUpdate = "PropagationUpdate",
}
