import { VoxelSubstanceType } from "Meta/index";
export declare const QueuesManager: {
    _numChunksRebuilding: number;
    _numRGBLightUpdates: number;
    _numRGBLightRemoves: number;
    _RGBLightRemoveQue: number[][];
    _RGBLightUpdateQue: number[][];
    _worldColumnSunLightPropMap: Record<string, number>;
    _worldColumnSunLightPropQue: number[][];
    _chunkRebuildQueMap: Record<string, Record<VoxelSubstanceType | "all", boolean>>;
    _chunkRebuildQue: number[][];
    __statesSAB: SharedArrayBuffer;
    __states: Uint32Array;
    $INIT(): void;
    addWorldColumnToSunLightQue(x: number, z: number): void;
    runWorldColumnSunLightAndUpateQue(): Promise<void>;
    awaitAllWorldColumnSunLightProp(): Promise<boolean>;
    areWorldColumnSunLightUpdatsDone(): boolean;
    awaitAllSunLightUpdatesAtMaxY(): Promise<boolean>;
    areAllSunLightUpdatesAtMaxYDone(): boolean;
    awaitAllSunLightUpdates(): Promise<boolean>;
    areAllSunLightUpdatesDone(): boolean;
    addToRGBUpdateQue(x: number, y: number, z: number): void;
    addToRGBRemoveQue(x: number, y: number, z: number): void;
    runRGBUpdateQue(): void;
    runRGBRemoveQue(): void;
    awaitAllRGBLightUpdates(): Promise<boolean>;
    awaitAllRGBLightRemove(): Promise<boolean>;
    areRGBLightUpdatesAllDone(): boolean;
    areRGBLightRemovesAllDone(): boolean;
    addToRebuildQue(x: number, y: number, z: number, substance: VoxelSubstanceType | "all"): void;
    runRebuildQue(): void;
    awaitAllChunksToBeBuilt(): Promise<boolean>;
};
