import { VoxelModelData } from "../VoxelModel.types";

export const stair: VoxelModelData = {
  id: "dve_simple_stair",
  relationsSchema: [],
  shapeStateSchema: [
    {
      name: "placement",
      type: "string",
      values: {
        0: "down",
        1: "up",
        2: "north",
        3: "south",
        4: "east",
        5: "west",
      },
    },
    {
      name: "direction",
      type: "string",
      values: {
        0: "south",
        1: "north",
        2: "east",
        3: "west",
      },
    },
    {
      name: "connected",
      type: "string",
      values: {
        0: "false",
        1: "true",
      },
    },
  ],
  arguments: {
    texture: {
      type: "texture",
    },
  },
  shapeStatesConditonalNodes: {},

  shapeStatesNodes: {
    "placement=up,direction=north,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        position: [0, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_west_east",
        position: [0, 0, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=up,direction=south,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        position: [0, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_west_east",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=up,direction=east,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        position: [0, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_south_north",
        position: [0.5, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=up,direction=west,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        position: [0, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_south_north",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=down,direction=north,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_west_east",
        position: [0, 0.5, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=down,direction=south,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_west_east",
        position: [0, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=down,direction=east,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_south_north",
        position: [0.5, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=down,direction=west,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_south_north",
        position: [0, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],

    "placement=north,direction=north,connected=false": [
      {
        id: "base",
        position: [0, 0, 0.5],
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_west_east",
        position: [0, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=north,direction=south,connected=false": [
      {
        id: "base",
        position: [0, 0, 0.5],
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_west_east",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=north,direction=east,connected=false": [
      {
        id: "base",
        position: [0, 0, 0.5],
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_up_down",
        position: [0.5, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=north,direction=west,connected=false": [
      {
        id: "base",
        position: [0, 0, 0.5],
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_up_down",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],

    "placement=south,direction=north,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_west_east",
        position: [0, 0.5, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=south,direction=south,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_west_east",
        position: [0, 0, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=south,direction=east,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_up_down",
        position: [0.5, 0, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=south,direction=west,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_up_down",
        position: [0, 0, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],

    "placement=east,direction=north,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        position: [0.5, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_south_north",
        position: [0, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=east,direction=south,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        position: [0.5, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_south_north",
        position: [0, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=east,direction=east,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        position: [0.5, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_up_down",
        position: [0, 0, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=east,direction=west,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        position: [0.5, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_up_down",
        position: [0, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],

    "placement=west,direction=north,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_south_north",
        position: [0.5, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=west,direction=south,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_south_north",
        position: [0.5, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=west,direction=east,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_up_down",
        position: [0.5, 0, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=west,direction=west,connected=false": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_quater_cube_up_down",
        position: [0.5, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],

    //connected
    "placement=up,direction=north,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        position: [0, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0.5, 0, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=up,direction=south,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        position: [0, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0, 0, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=up,direction=east,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        position: [0, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0.5, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=up,direction=west,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        position: [0, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],

    "placement=down,direction=north,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0.5, 0.5, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=down,direction=south,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0, 0.5, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=down,direction=east,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0.5, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=down,direction=west,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_down_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],

    "placement=north,direction=north,connected=true": [
      {
        id: "base",
        position: [0, 0, 0.5],
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0.5, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=north,direction=south,connected=true": [
      {
        id: "base",
        position: [0, 0, 0.5],
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=north,direction=east,connected=true": [
      {
        id: "base",
        position: [0, 0, 0.5],
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0.5, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=north,direction=west,connected=true": [
      {
        id: "base",
        position: [0, 0, 0.5],
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],

    "placement=south,direction=north,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0.5, 0.5, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=south,direction=south,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0, 0.5, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=south,direction=east,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0.5, 0, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=south,direction=west,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_south_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0, 0, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],

    "placement=east,direction=north,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        position: [0.5, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0, 0.5, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=east,direction=south,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        position: [0.5, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=east,direction=east,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        position: [0.5, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0, 0, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=east,direction=west,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        position: [0.5, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],

    "placement=west,direction=north,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0.5, 0.5, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=west,direction=south,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0.5, 0.5, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=west,direction=east,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0.5, 0, 0.5],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
    "placement=west,direction=west,connected=true": [
      {
        id: "base",
        geometryId: "dve_half_cube_west_half",
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
      {
        id: "up",
        geometryId: "dve_eighth_cube",
        position: [0.5, 0, 0],
        inputs: {
          "@upTex": "@texture",
          "@downTex": "@texture",
          "@northTex": "@texture",
          "@southTex": "@texture",
          "@eastTex": "@texture",
          "@westTex": "@texture",
        },
      },
    ],
  },
};
