export enum StairStates {
  DownNorth,
  DownSouth,
  DownEast,
  DownWest,
  UpNorth,
  UpSouth,
  UpEast,
  UpWest,
  DownNorthEast,
  DownNorthWest,
  DownSouthEast,
  DownSouthWest,
  UpNorthEast,
  UpNorthWest,
  UpSouthEast,
  UpSouthWest,
}

export const StairStatesArray: StairStates[] = [
  StairStates.DownNorth,
  StairStates.DownSouth,
  StairStates.DownEast,
  StairStates.DownWest,
  StairStates.UpNorth,
  StairStates.UpSouth,
  StairStates.UpEast,
  StairStates.UpWest,
  StairStates.DownNorthEast,
  StairStates.DownNorthWest,
  StairStates.DownSouthEast,
  StairStates.DownSouthWest,
  StairStates.UpNorthEast,
  StairStates.UpNorthWest,
  StairStates.UpSouthEast,
  StairStates.UpSouthWest,
];
