
rm kernel.js
rm kernel.wasm
INCLUDE_DIRS=$(find ./libs -type d | sed 's/^/-I/')
emcc $(find ./ -name '*.cpp')  -o kernel.js $INCLUDE_DIRS -s EXPORTED_FUNCTIONS=_sabTest,_bufferToDBO,_DVE_BRIDGE_RUN_WORLD_SUN_LIGHT,_DVE_BRIDGE_REMOVE_RGB_LIGHT,_DVE_BRIDGE_UPDATE_RGB_LIGHT,_DVE_BRIDGE_REMOVE_SUN_LIGHT,_DVE_BRIDGE_UPDATE_SUN_LIGHT,_DVE_BRIDGE_SYNC_VOXEL_TAGS,_DVE_BRIDGE_SYNC_VOXEL_PALETTE,_DVE_BRIDGE_SYNC_VOXEL_SUBSTANCE_PALETTE,_DVE_BRIDGE_SYNC_VOXEL_SUBSTANCE_TAGS,_DVE_BRIDGE_SYNC_CHUNK_TAGS,_DVE_BRIDGE_SYNC_CHUNK,_DVE_BRIDGE_UN_SYNC_CHUNK,_DVE_BRIDGE_SYNC_COLUMN_TAGS,_DVE_BRIDGE_SYNC_COLUMN,_DVE_BRIDGE_UN_SYNC_COLUMN,_DVE_BRIDGE_SYNC_REGION_TAGS,_DVE_BRIDGE_SYNC_REGION,_DVE_BRIDGE_UN_SYNC_REGION -s EXPORTED_RUNTIME_METHODS=ccall,cwrap -s MODULARIZE=1 -s EXPORT_NAME='DVEKernelWASM' -s DISABLE_EXCEPTION_CATCHING=0 -s SHARED_MEMORY=1 -s USE_PTHREADS=1
echo 'export' | cat - kernel.js > temp && mv temp kernel.js
cp ./kernel.js ../src/Kernel/kernel.js
cp ./kernel.wasm ../../../testing/static/kernel.wasm
